version: '3'
services:
  usecase1ag:
    image: ghcr.io/jabrena/usecase1-api-gateway:buildpacks-jvm.0.0.1-SNAPSHOT
    ports:
      - 9191:9191
    depends_on:
      - "usecase1a"
    networks:
      - usecase1
  usecase1a:
    image: ghcr.io/jabrena/usecase1-a:buildpacks-jvm.0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - USE_CASE_B=http://usecase1b:8081/
    depends_on:
      - "usecase1b"
    networks:
      - usecase1
  usecase1b:
    image: ghcr.io/jabrena/usecase1-b:buildpacks-jvm.0.0.1-SNAPSHOT
    ports:
      - 8081:8081
    networks:
      - usecase1
networks:
  usecase1: