version: '3'
services:
  usecase1ag:
    image: ghcr.io/jabrena/usecase1-api-gateway:buildpacks-native.0.0.1-SNAPSHOT
    ports:
      - 9192:9192
    environment:
      - SERVER_PORT=9192
      - USE_CASE_A=http://usecase1a:8084/
      - USE_CASE_AN=http://usecase1an:7084/
    depends_on:
      - "usecase1an"
    networks:
      - usecase1
  usecase1a:
    image: ghcr.io/jabrena/usecase1-a:buildpacks-jvm.0.0.1-SNAPSHOT
    ports:
      - 8084:8084
    environment:
      - SERVER_PORT=8084
      - USE_CASE_B=http://usecase1b:8081/
    depends_on:
      - "usecase1b"
    networks:
      - usecase1
    #profiles:
    #  - donotstart
  usecase1an:
    image: ghcr.io/jabrena/usecase1-a:buildpacks-native.0.0.1-SNAPSHOT
    ports:
      - 7084:7084
    environment:
      - SERVER_PORT=7084
      - USE_CASE_B=http://usecase1bn:7081/
    depends_on:
      - "usecase1bn"
    networks:
      - usecase1
  usecase1b:
    image: ghcr.io/jabrena/usecase1-b:buildpacks-jvm.0.0.1-SNAPSHOT
    ports:
      - 8081:8081
    networks:
      - usecase1
    #profiles:
    #  - donotstart
  usecase1bn:
    image: ghcr.io/jabrena/usecase1-b:buildpacks-native.0.0.1-SNAPSHOT
    ports:
      - 7081:7081
    environment:
      - SERVER_PORT=7081
    networks:
      - usecase1
networks:
  usecase1:
