version: '3'
services:
  usecase1a:
    image: ghcr.io/jabrena/use-case1-a:buildpacks-native.0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - USE_CASE_B=http://usecase1b:8081/
    depends_on:
      - "usecase1b"
    networks:
      - usecase1
  usecase1b:
    image: ghcr.io/jabrena/use-case1-b:buildpacks-native.0.0.1-SNAPSHOT
    ports:
      - 8081:8081
    networks:
      - usecase1
networks:
  usecase1:
