server.port: ${SERVER_PORT:9191}
management.endpoints.web.exposure.include: "*"

spring.cloud.gateway.routes:

  - id: usecase1a
    uri: ${USE_CASE_A:http://localhost:8080/}
    predicates:
      - Path=/jvm/
    filters:
      - SetPath=/
  - id: usecase1an
    uri: ${USE_CASE_AN:http://localhost:8080/}
    predicates:
      - Path=/native/
    filters:
      - SetPath=/      

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
