name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  name: Run Docker Examples
  runs-on: ubuntu-latest
  timeout-minutes: 10
  steps:
    - uses: actions/checkout@v2
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'dev'
        java-version: '17'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cache: 'maven'
    - name: Run Java Hello World
      run: |
        #
        # Setup musl toolchain
        #
        ./setup-musl.sh
        cd 1_hello_world
        ./build.sh
    - name: Run Java jwebserver
      run: |
        cd jwebserver
        ./build-jwebserver.sh