name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gcc libz-dev upx
          sudo rm -rf /var/lib/apt/lists/*
          export VERSION=22.3.0
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$VERSION/graalvm-ce-java19-linux-amd64-$VERSION.tar.gz
          sudo tar -xvzf graalvm-ce-$VERSION-linux-amd64.tar.gz
          sudo rm graalvm-ce-linux-amd64-$VERSION.tar.gz
          sudo /graalvm-ce-$VERSION/bin/gu install native-image
          export PATH=/graalvm-ce-$VERSION/bin:$PATH

      - name: hello-world
        run: |
          cd hello-world
          ./build-hello.sh
