name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: hello-world
        run: |          
          cd hello-world
          ./prepare-environment.sh
          ./build-hello.sh