name: Poliglot Docker Builds

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'poliglot_docker_builds/**'
      - '.github/workflows/poliglot_docker_builds.yml'
permissions:
  contents: read
jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Run musl setup
        run: |
          ./setup-musl.sh

      - name: Run Java Hello World
        run: |
          cd poliglot_docker_builds/1_java_hello_world
          ./build-hello-world.sh

      - name: Run Java jwebserver
        run: |
          cd poliglot_docker_builds/2_java_jwebserver
          ./build-all.sh

      - name: Run Spring-boot
        run: |
          cd poliglot_docker_builds/3_java_spring_boot
          ./build-spring-boot.sh

      - name: Run Node.js with Express
        run: |
          cd poliglot_docker_builds/4_nodejs_express
          ./build-nodejs.sh

      - name: Run Python http.server & django
        run: |
          cd poliglot_docker_builds/5_python
          ./build-python.sh