name: Usecase 1

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Run musl setup
        run: |
          ./setup-musl.sh

      - name: Run usecase1_rest_comms_a
        run: |
          cd usecase1_rest_comms_a
          ./build-spring-boot.sh

      - name: Run usecase1_rest_comms_b
        run: |
          cd usecase1_rest_comms_b
          #./build-spring-boot.sh          

      # Register Docker images
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      # In previous scripts, the images are built
      #- name: Build Docker Image
      #  run: mvn clean spring-boot:build-image

      - name: Push image to GitHub Container Registry
        run: |
          #docker images use_case1_a
          docker images ghcr.io/jabrena/101-docker
          docker images 
            
          IMAGE_ID=ghcr.io/jabrena/101-docker:use-case1-a-buildpacks-jvm.0.0.1-SNAPSHOT
          docker push $IMAGE_ID
          
          #IMAGE_ID=ghcr.io/use_case1_b:buildpacks-jvm.0.0.1-SNAPSHOT
          #docker push $IMAGE_ID