name: Usecase Building Blocks

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'usecases/demo/**'
      - '.github/workflows/usecases_build.yml'
permissions:
  contents: read
jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'dev'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Build image & push
        run: |
          cd usecases/demo
          mvn spring-boot:build-image \
            --batch-mode --no-transfer-progress \
            -Dspring-boot.build-image.publish=true \
            -Dspring-boot.build-image.docker.builderRegistry.url=https://index.docker.io/v1/ \
            -Dspring-boot.build-image.docker.builderRegistry.token=${{ secrets.DOCKERHUB_TOKEN }} \
            -Dspring-boot.build-image.docker.builderRegistry.user=${{ secrets.DOCKERHUB_USERNAME }}